version: "3.8"
services:
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:54321
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iamon
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init/:/docker-entrypoint-initdb.d
  spring:
      container_name: spring
      image: iamon-spring:1.0.0
      build: .
      ports:
        - 8080:8080
      environment:
        - DATABASE_URL=jdbc:postgresql://db:5432/iamon
        - DATABASE_USERNAME=postgres
        - DATABASE_PASSWORD=postgres
      depends_on:
        - db